#!/bin/sh
#
# Runs before git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#

echo post-flow-release-finish start

NAME=$1
ORIGIN=$2
BRANCH=$3

# files=`exec git diff-tree -r master..develop --name-only --diff-filter=dr src`

HOOK_ERROR=0
java=false

# Implement your script here.

branch=$(git symbolic-ref --short HEAD)
echo $branch

# for FILE in `exec git diff-tree -r master..$branch --name-only --diff-filter=ACM` ; do
#     rsync -R "$FILE" diff || { echo "Failed to publish $FILE"; exit 1; }
# done

. .git/hooks/modules/deploy.sh

for FILE in `exec git diff-tree -r master..$branch --name-only --diff-filter=ACM src` ; do
    prepareDeploy $FILE
done

buildDeploy

echo post-flow-release-finish end

# To terminate the git-flow action, return a non-zero exit code.
exit 0
