#!/bin/sh
#
# Runs before git flow feature finish
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#

NAME=$1
ORIGIN=$2
BRANCH=$3

# files=`exec git diff-tree -r master..develop --name-only --diff-filter=dr src`

HOOK_ERROR=0
java=false

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

branch=$(git symbolic-ref --short HEAD)
. "$HOOKS_DIR/modules/deploy.sh"

for FILE in `exec git diff-tree -r master..$branch --name-only --diff-filter=ACM src` ; do
    prepareDeploy $FILE
    if [ $? -ne 0 ]; then
      exit 1
  fi

done

buildDeploy
if [ $? -ne 0 ]; then
    exit 1
fi

# To terminate the git-flow action, return a non-zero exit code.
exit 0
